### PR TITLE
Adding ETHOS-specific changes for Splunk Docker images

### PR DESCRIPTION
**Pull request by eadasiak**
For the ETHOS-specific changes, I've added two files that can be used to create the ethos-splunkforwarder image:

The `Dockerfile-ethos` file just adds a different entrypoint file to the stock Splunk Docker image

The `ethos-entrypoint.sh` file is based off of the stock Splunk version, but has these additions:
- the SSL certs for forward-servers can be provided via environment variables and are exported onto the filesystem
- Up to 10 HEC endpoints can be configured via environment variables.
- The global HEC setting for SSL can be set via an environment variable

Examples:
    "SPLUNK_HEC_USESSL": "false",
    "SPLUNK_HEC_1_TOKEN": "blahblahblah",
    "SPLUNK_HEC_1": "ethos-hvc",
    "SPLUNK_HEC_1_OUTPUTGROUP": "splunk-us-hvc-internal.adobelaas.com_8200",
    "SPLUNK_HEC_2_TOKEN": "blahblahblahbooger",
    "SPLUNK_HEC_2": "ethos-lvc",
    "SPLUNK_HEC_2_OUTPUTGROUP": "splunk-us-lvc-internal.adobelaas.com_8200"

### CODE REVIEW

**Comment by ts3ng** [comment]
@eadasiak looks good! +1 on not mapping the host volumes for configurations. I will merge.

**Comment by ts3ng** [comment]
I will setup new tag for the new docker file you included.

**Comment by ts3ng** [comment]
@eadasiak for now i set the dockerbuild to heavyforwarder-ethos we can change it to somethign else.  I know matt was talking about version conventions (i'm still confused on what they are suppose to be) so perhaps we'll switch the tags accordingly once we get that straightened out.  we can discuss next week. here is the builds: https://hub.docker.com/r/adobeplatform/docker-splunk/builds/

**Comment by eadasiak** [comment]
thanks much, @ts3ng!

**Pull request merged**
